# needed for proper color support
# - screen-256color - bets compatibility
# - tmux-256color - most popular
# - tmux-direct - newest option
set -g default-terminal "tmux-direct"

set -g prefix C-a
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-window-option -g automatic-rename on
set-option -g renumber-windows on

bind R source-file ~/.config/tmux/tmux.conf
bind r source-file ~/.config/tmux/tmux.conf

# # pane navigation
# bind -r h select-pane -L # move left
# bind -r j select-pane -D # move down
# bind -r k select-pane -U # move up
# bind -r l select-pane -R # move right
# bind > swap-pane -D # swap current pane with the next one
# bind < swap-pane -U # swap current pane with the previous one

# new panes and windows
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navigation
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window

# copy mode
setw -g mode-keys vi

## vim-style selection and yank
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi r send-keys -X rectangle-toggle

bind Enter copy-mode # enter copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'tmux-plugins/tmux-copycat'
#set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
## session restore
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on' # restore session when tmux server starts
set -g @continuum-boot 'off' # start tmux server on boot
set -g @continuum-save-interval '15' # autosave interval in minutes

# status line
# set-option -g status-position top # bottom
set -g status-style "bg=default"
# left side
set -g status-left-length 100
set -g status-left " #[fg=brightblue] #S #[fg=magenta]│ "
# windows
set -g window-status-style "fg=default"
set -g window-status-separator " #[fg=white]| " # bigger line - │
set -g window-status-format "#I.#W"
set -g window-status-last-style "fg=default"
set -g window-status-current-style "fg=green,bold"
set -g window-status-current-format "#I.#W"
# right side
set -g status-right-length 100
set -g status-right "#[fg=red]"
set -ga status-right "#{?mouse,, off }"
set -ga status-right "#{?window_zoomed_flag, ,}"
set -ga status-right "#[fg=default]%Y-%m-%d %H:%M"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# plugin setup

## continuum
set -g @continuum-restore 'on'

## sessionx setup
set -g @sessionx-bind 'w'
set -g @sessionx-window-mode 'on'

## tv + sesh
bind-key "t" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh

